### ISSUE TITLE
Tartufo showing error on window machine

### ISSUE THREAD

**Issue by swanand-patil** [godaddy/tartufo#140]
Hi Team

We have tried below command to generate tartufo output in file ( print output in file )

tartufo -od "tartufo_report" scan-local-repo .

After execute command, we are getting error ( check attached screen shot for reference ).  I think error occurs, because it is trying to create folder “tartufo-scan-results-2020-11-02T16:54:52.950660” on window machine but Colon ( : ) not allowed in folder name on window.

Can you please help us on this point ?  let me know if you have any alternate solution for this issue ?

![tartufo window issue](https://user-images.githubusercontent.com/10205565/98543991-524cef80-22b9-11eb-8050-0a8143055d70.png)
![Tartufo GIT repo](https://user-images.githubusercontent.com/10205565/98544019-5bd65780-22b9-11eb-839d-7994de13be1c.png)

**Comment by tarkatronic** [comment]
Hi @swanand-patil, thank you for your thorough bug report! It appears you are correct on the `:` being the problem here. I will make sure that this bug gets fixed in our next release. We are currently working toward a 2.1 feature release, but if that is still looking too far out then I will work on a 2.0.2 bugfix release.

I believe this will also warrant the need for us to work on #95 in order to run our tests against Windows as well.

FWIW if you need an immediate workaround, this should be working in WSL.
