### ISSUE TITLE
Entropy exclusion regexes don't look at surrounding text

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#217]
## 🐛 Bug Report

Currently, the [--exclude-entropy-patterns](https://tartufo.readthedocs.io/en/stable/features.html#entropy-limiting) feature only allows you to exclude based on the exact matched string, rather than being able to match based on the surrounding text. This means that, as an example, I cannot explicitly exclude just SHA hashes in GitHub actions.

## To Reproduce

1. Set up a GitHub Action using a SHA hash, such as:
    
    ```yaml
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    ```

1. Set up an exclusion pattern that [should match this](https://pythex.org/?regex=%5E%5Cs%2B(%3F%3A-%20)%3Fuses%5C%3A%20actions%5C%2F.*%5C%40%5Ba-z0-9%5D%7B40%7D%24&test_string=%20%20%20%20%20-%20uses%3A%20actions%2Fcheckout%405a4ac9002d0be2fb38bd78e4b4dbde5606d7042f%0A%20%20%20%20%20%20%20uses%3A%20actions%2Fsetup-python%40dc73133d4da04e56a135ae2246682783cc7c7cb6%0A%20%20%20%20%20-%20uses%3A%20actions%2Fcache%40c64c572235d810460d0d6876e9c705ad5002b353%0A&ignorecase=0&multiline=1&dotall=0&verbose=0):
   
   ```toml
   exclude-entropy-patterns = [
       '.github/workflows/(.*)\.yml::^\s+(?:- )?uses\: actions\/.*\@[a-z0-9]{40}$'
   ]
   ```

1. Run a scan.

## Expected Behavior

There should be no match in the scan.

## Potential Cause / Fix

It appears that the issue stems from the way that entropy is evaluated, here: https://github.com/godaddy/tartufo/blob/ee84de8d6754a470d2777418bd2f9b895dd54211/tartufo/scanner.py#L355-L374

Specifically:
* A "chunk" is split into individual lines.
* Those lines are split into individual words.
* Those words are split into "strings".
* Those "strings" are evaluated for their entropy value.
* Exclusion matching is performed based solely on the "strings" themselves.

So when an individual "string" is evaluated, it has no visibility to the line, or even the word, from which it was extracted. It seems that the solution would be to pass along either the word or the line from which the string was extracted, and perform exclusion matching on that value instead.

**Comment by rbailey-godaddy** [comment]
Yuck. So talking this through, we have chunks consist of one or more lines which consist of one or more words, and a word might have high entropy, but we want to exclude it based on a regex that may include context surrounding the word.

If we started (as a talking point, anyway) with the assertion that we didn't want to entertain multi-line regex patterns, then the naive approach would be to insert processing between L361 and L362 so that `line` is reduced to only those substrings that do not match any exclusion substring, and then we proceed with splitting that remainder to look for entropy.

However, this is hard to reason about in the abstract (especially with multiple regex candidates) and is going to involve a lot of hacking and slashing, so to speak.

Coming from the other direction, as you point out, absolutely nothing knows where in `line` (or `chunk`) a given `word` appears, so it is impossible to say with assurance whether or not it is contained within a substring that matches an exclusion regex.

I guess my first straw proposal would be:
* State explicitly that exclusion patterns are single-line (i.e. we consider only `line` not `chunk` content when matching, reducing the intensity of the regex work in the last step)
* We rewrite L362-L366 so that the exact position of `string` in `line` is known
* We pass this position (and probably `line`) to `evaluate_entropy_string()` as arguments so that
* When evaluating, only when we find `string` has high entropy, we perform regex findall (or finditer) on `line` and ignore `string` if we find it is entirely contained within a matching substring

**Comment by tarkatronic** [comment]
> Yuck. So talking this through, we have chunks consist of one or more lines which consist of one or more words, and a word might have high entropy, but we want to exclude it based on a regex that may include context surrounding the word.

So, this is almost the complete story. Let's take a more concrete example: https://github.com/godaddy/tartufo/blob/ee84de8d6754a470d2777418bd2f9b895dd54211/tartufo/scanner.py#L27-L28

Let's say that is the entirety of the `chunk`.

First, it will be split into individual `lines`: `BASE64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="`, and `HEX_CHARS = "1234567890abcdefABCDEF"`

Next, tracking through the processing, the first line will be split into `words`: `BASE64_CHARS`, `=`, and `"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="`.

Finally, each of those `words` will be split into `strings`: `BASE64`, `CHARS`, `=`, and `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=` (Note the lack of quotes this time around.)

Going back again to the example of a GitHub Action SHA, it would work similarly, taking this: https://github.com/godaddy/tartufo/blob/ee84de8d6754a470d2777418bd2f9b895dd54211/.github/workflows/ci.yml#L29

and breaking it down into the following:
* `words`: `uses:`, and `actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f`
* `strings`: `uses` `actions/checkout`, and `5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f`.

I'm sure there was a point to telling all of this, aside from being technically correct. But I can't think of what it is off the top of my head.

**Comment by rbailey-godaddy** [comment]
> * `words`: `uses:`, and `actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f`
> * `strings`: `uses` `actions/checkout`, and `5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f`.

Actually `get_strings_of_set()` is even more bizarre than I vaguely recalled. Just to get you warmed up:

```
>>> import util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sbailey/GitHub/tartufo/tartufo/util.py", line 2, in <module>
    import json
  File "/usr/lib/python3.9/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/usr/lib/python3.9/json/decoder.py", line 3, in <module>
    import re
  File "/usr/lib/python3.9/re.py", line 124, in <module>
    import enum
  File "/usr/lib/python3.9/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/home/sbailey/GitHub/tartufo/tartufo/types.py", line 3, in <module>
    from dataclasses import dataclass
  File "/usr/lib/python3.9/dataclasses.py", line 3, in <module>
    import copy
  File "/usr/lib/python3.9/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python3.9/weakref.py", line 22, in <module>
    from _weakrefset import WeakSet, _IterationGuard
  File "/usr/lib/python3.9/_weakrefset.py", line 6, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/sbailey/GitHub/tartufo/tartufo/types.py)
>>>
```
So I resort to thinking the action through (after being distracted by L200 OMG string concatenation in inner loop) and `b64_strings` actually will contain only `5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f` because `uses` and `actions/checkout` are both shorter than `threshold` (default 20 characters) -- and both would have been rejected anyway by `hex_strings` which will contain the same one number.

Then I get distracted by the philosophical ramifications of `threshold`'s default setting and feel happy because the usual AWS credential components are all 20 characters or longer, but... are there possibly other common hashes used for sensitive material that might be shorter, or different?

For example from my system's `/etc/shadow` file, obfuscated by swapping a few characters:

`$1$SlhiQ2ZF$KusSU.GcrueRsVJXAj6zw1`

This would be ignored entirely because the longest base64-compatible substring is only 16 characters long, but any knowledgeable human looking at it would likely recognize it as a Linux password hash (which unfortunately for us uses a family of mutant base64-ish hash methods for some of the components).

Actually, I think I'll write this up as a separate issue, because (at least on Debian) the `crypt (5)` manpage is very explicit and it would be easy to derive a set of regexes that would match all valid password hashes.

Now I've forgotten where I was going with this, too. ;-)
