### ISSUE TITLE
Do not traverse directories with --config

### ISSUE THREAD

**Issue by rbailey-godaddy** [godaddy/tartufo#475]
## Feature Request

When I say `tartufo --config foo`, tartufo looks for `foo` in the stated location; but if it is not found, it starts moving upward in the directory hierarchy looking for a usable file with the same name.

## Describe the solution you'd like

Tartufo should not perform unrestricted directory traversals looking for configuration files. It should use exactly the file I specify, or use nothing.

**Comment by jsimmons1-godaddy** [comment]
Have you confirmed that this is actually happening? I did some fairly extensive testing, and I believe that _only_ when you have not specified `--config`, and it's using the default config file name(s) will it successfully traverse. The code looks like it's trying to attempt to traverse upwards, but:

1. by the time it gets to that code, the config file to be used is already converted to a full, unambiguous path (thus the code that appears like it would try to use parents just doesn't do anything except use the same path you specified)
2. the config file to be used has already been found to exist (otherwise an error occurs), so it always finds it

I could find no case in which it actually traverses upwards looking for a file specified by `--config`
