### ISSUE TITLE
Tartufo does not process rule-patterns set up in default config file set up in repository being scanned. 

### ISSUE THREAD

**Issue by emayuri-godaddy** [godaddy/tartufo#476]
## 🐛 Bug Report

If the rule-patterns are set up in the project's default config file i.e. pyproject.toml or tartufo.toml, tartufo does not process these additional rule-patterns when a scan is performed.

## To Reproduce

Using the tartufo repository itself as an example:

- Add rule patterns in the projects default config file https://tartufo.readthedocs.io/en/stable/configuration.html#rule-patterns:~:text=the%20command%20line.-,Rule%20Patterns,%C2%B6,-New%20in%20version
- Run tartufo scan `tartufo -vvv scan-local-repo .`

## Expected Behavior

Tatufo should process the rule-patterns setup in the config file along with the rest of the rules set up in default_regexes.json

https://github.com/godaddy/tartufo/issues/469#issuecomment-1483219833

**Comment by mgaspar-godaddy** [comment]
Sorry if I didn't explain things well in [#469 ](https://github.com/godaddy/tartufo/issues/469#issuecomment-1483219833), but the issue is more complex and isn't stated correctly here. I believe it is actually related to #469 and how configs are being merged.

Using rule-patterns in a default tartufo.toml or pyproject.toml works fine as long as you are not specifying another config using the `--config` option.

To reproduce the error using the tartufo repository itself I would do this:

- Add rule patterns in the projects default config file https://tartufo.readthedocs.io/en/stable/configuration.html#rule-patterns:~:text=the%20command%20line.-,Rule%20Patterns,%C2%B6,-New%20in%20version
- Run tartufo scan and not that the rule patterns are included `tartufo -vvv scan-local-repo .`
- If you look at the Rule object that is in the output you should be able to see the rule named "RSA private key 2" present there.
- Now create an alternative config file called `alt-tartufo.toml` and add the following content:
```toml
[tool.tartufo]
repo-path = "."
json = false
cleanup = true
entropy = true
exclude-entropy-patterns = []
exclude-path-patterns = []
exclude-signatures = []
```

- Now run `tartufo -vvv --config alt-tartufo.toml scan-local-repo .`
- If you look at the Rule object that is printed in the output you should notice that the rule named "RSA private key 2" is not longer present.
